apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
spec:
  restartPolicy: Never
  containers:
  - name: postgres
    image: {{ postgres.image.name }}
    resources:
      requests:
        memory: {{ postgres.resources.requests.memory }}
      limits:
        memory: {{ postgres.resources.limits.memory }}
    ports:
    - containerPort: {{ postgres.port.container }}
      hostPort: {{ postgres.port.host }}
      hostIP: {{ postgres.port.ip }}
      protocol: tcp
    env:
    - name: POSTGRES_DB
      value: {{ postgres.dbname }}
    - name: POSTGRES_USER
      value: {{ postgres.user }}
    - name: POSTGRES_PASSWORD
      value: {{ postgres.password }}
    volumeMounts:
    - mountPath: /var/lib/postgresql/data
      name: pgdata
  volumes:
  - name: pgdata
    persistentVolumeClaim:
      claimName: postgres-data
