apiVersion: v1
kind: Pod
metadata:
  name: {{ projectname }}-postgres-pod
spec:
  restartPolicy: OnFailure
  containers:
  - name: postgres
    image: {{ postgres.image.name }}
    securityContext:
      allowPrivilegeEscalation: false
      privileged: false
      capabilities:
        add: []
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
      seLinuxOptions: {}
    resources:
      requests:
        memory: {{ postgres.resources.requests.memory }}
      limits:
        memory: {{ postgres.resources.limits.memory }}
    ports:
    - containerPort: {{ postgres.port.container }}
      hostPort: {{ postgres.port.host }}
      hostIP: {{ postgres.port.ip }}
      protocol: tcp
    env:
    - name: POSTGRES_DB
      value: {{ postgres.dbname }}
    - name: POSTGRES_USER
      value: {{ postgres.user }}
    - name: POSTGRES_PASSWORD
      value: {{ postgres.password }}
    volumeMounts:
    - mountPath: /var/lib/postgresql/data
      name: pgdata
  volumes:
  - name: pgdata
    persistentVolumeClaim:
      claimName: {{ projectname }}-postgres-data
