apiVersion: v1
kind: Pod
metadata:
  name: zabbix-server-pod
spec:
  restartPolicy: OnFailure
  hostNetwork: true
  containers:
  - name: server
    image: {{ server.image.name }}
    securityContext:
      allowPrivilegeEscalation: false
      privileged: false
      capabilities:
        add: []
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
      seLinuxOptions: {}
    resources:
      requests:
        memory: {{ server.resources.requests.memory }}
      limits:
        memory: {{ server.resources.limits.memory }}
    env:
    - name: DB_SERVER_HOST
      value: {{ server.database.host }}
    - name: DB_SERVER_PORT
      value: {{ server.database.port }}
    - name: POSTGRES_DB
      value: {{ server.database.dbname }}
    - name: POSTGRES_USER
      value: {{ server.database.username }}
    - name: POSTGRES_PASSWORD
      value: {{ server.database.password }}
    - name: ZBX_DEBUGLEVEL
      value: {{ server.loglevel }}
    - name: ZBX_TIMEOUT
      value: {{ server.timeout }}
    volumeMounts:
    - mountPath: /etc/zabbix/zabbix_server.conf
      name: zabbix-server-config
  - name: web
    image: {{ web.image.name }}
    resources:
      requests:
        memory: {{ web.resources.requests.memory }}
      limits:
        memory: {{ web.resources.limits.memory }}
    env:
    - name: DB_SERVER_HOST
      value: {{ web.database.host }}
    - name: DB_SERVER_PORT
      value: {{ web.database.port }}
    - name: POSTGRES_DB
      value: {{ web.database.dbname }}
    - name: POSTGRES_USER
      value: {{ web.database.username }}
    - name: POSTGRES_PASSWORD
      value: {{ web.database.password }}
    - name: ZBX_SERVER_HOST
      value: {{ web.server.ip }}
    - name: ZBX_SERVER_PORT
      value: {{ web.server.port }}
  volumes:
  - name: zabbix-server-config
    hostPath:
      path: /opt/zabbix/zabbix_server.conf
